apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170167431
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170167431
    app.kubernetes.io/part-of: test-app-170167431
  name: java-quarkus-170167431
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170167431
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170167431
    spec:
      containers:
      - image: quay.io/hacdev/3owc273d-tenant/test-app-170167431/java-quarkus-170167431@sha256:e2725dda3fc4dfb6b135f981eb5749d93e77b505b5f58b813c3afdf7d46070aa
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
